<?php

namespace modules\jonson\services;

use yii\base\Component;

/**
 * Checks a finished answer for claims about who Jon has worked for or with before the
 * visitor sees it. Plain code, no API call, so a passing answer costs no time. The page
 * holds the answer until it's complete, so this sits in a gap that already exists.
 *
 * Two rules, both against what Jonson was actually given:
 *
 * 1. NO UNKNOWN CLIENTS. A name put forward as work — "worked with X", "clients like
 *    X", "designed for X", or listed alongside a real client — must be someone Jon
 *    worked with: a client, a case study's client, a CV company, or a testimonial's
 *    company or person (FindContext::workNames). Merely appearing in what Jonson read
 *    isn't enough: Spotify is in its music background, not its client list. Names
 *    elsewhere (places, cameras, bands) are left alone: they aren't claims about work.
 * 2. EMPLOYMENT IS THE CV. "in-house at / employed by / joined X" needs X to be a CV
 *    company. "in-house at HSBC and Lloyds" fails: Lloyds is a client, not an employer.
 *
 * A failed answer is regenerated by the caller; see AskController. Prove changes here
 * with tools/jonson/claims.php (free replay over every stored suite answer).
 */
class ClaimCheck extends Component
{
    // Words that introduce an employer. Matched case-insensitively, then followed by
    // one or more names ("HSBC International and Lloyds Bank International").
    private const EMPLOYED = '(?:in[- ]house (?:at|with|for)|employed (?:at|by)|on (?:the )?staff (?:at|of)|(?:was|went|got) hired (?:at|by)|joined|my (?:time|years|days) (?:at|with) )';

    // Words that put a name forward as Jon's work: whatever names follow are clients.
    private const WORKED = '(?:worked (?:with|for|at|alongside)|work(?:ing)? (?:with|for)|done work for|did work for|(?:designed|built|redesigned|developed|delivered|made|created|branded|rebranded)(?: \\w+){0,3} for|clients?(?: \\w+){0,2} (?:like|such as|including|incl\\.?|e\\.g\\.)|(?:brands|names|companies|organisations|businesses|banks|firms|startups) (?:like|such as|including)|client list (?:includes|including)|(?:my|his) clients (?:include|have included|are))';

    // Words that don't identify anyone on their own: "UK" isn't Urban.co.uk, "Jersey"
    // isn't Jersey Post, "Bank" isn't Lloyds.
    private const GENERIC = ['and', 'company', 'ltd', 'limited', 'inc', 'plc', 'group', 'international', 'bank', 'co', 'com', 'uk', 'jersey'];

    // Small words allowed inside a name: "Government of Jersey", "The White Paper…".
    private const JOINERS = ['of', 'the', 'de', 'du', 'la', 'le', 'for'];

    /**
     * What's wrong with $answer: each name it shouldn't have put forward, and why.
     * [] when it's clean.
     *
     * @param string $context everything the model was given for this turn
     * @param string[] $employers CV company names (FindContext::employers)
     * @param string[] $clients everyone Jon worked with (FindContext::workNames)
     * @return array<array{name: string, problem: string}>
     */
    public function findings(string $answer, string $context, array $employers, array $clients): array
    {
        $text = $this->plain($answer);
        $found = [];
        foreach ($this->unknownClients($text, $context, $clients) as $name) {
            $found[$name] = ['name' => $name, 'problem' => "puts \"$name\" forward as Jon's work, but Jon has never worked with or for them"];
        }
        foreach ($this->notEmployers($text, $employers) as $name) {
            $found[$name] = ['name' => $name, 'problem' => "says Jon worked in-house at / was employed by \"$name\", but they were never his employer (see the CV)"];
        }

        return array_values($found);
    }

    /**
     * Names in the answer's prose that Jonson knows only from a VIP's private note
     * (AskController::hiddenNoteTerms) — the note shapes what's said, it is never said
     * back. Matched as written, case and all: "an energy app" is ordinary prose, "the
     * Department of Energy" is the note's. Chips are not prose (see withoutNoteChips).
     *
     * @param string[] $terms
     * @return array<array{name: string, problem: string}>
     */
    public function noteFindings(string $answer, array $terms): array
    {
        $text = $this->plain($answer);
        $found = [];
        foreach ($terms as $term) {
            if (preg_match('/(?<![\p{L}\p{N}])' . preg_quote($term, '/') . '(?![\p{L}\p{N}])/u', $text)) {
                $found[] = ['name' => $term, 'problem' => "names \"$term\", which you know only from your private note on this visitor and they haven't said themselves; use the note to choose what you say, never to name it or hint at it"];
            }
        }

        return $found;
    }

    /**
     * The answer with any [[next: …]] chip that names a note-only term removed — a chip
     * is a question put in the visitor's mouth, and "…like MyJE?" told Réka what Jon had
     * written about her. The rest of the block stands; an emptied block goes.
     *
     * @param string[] $terms
     */
    public function withoutNoteChips(string $answer, array $terms): string
    {
        if (!$terms || !preg_match('/\[\[next:([^\]]*)\]\]/u', $answer, $m, PREG_OFFSET_CAPTURE)) {
            return $answer;
        }
        $kept = array_filter(array_map('trim', explode('|', $m[1][0])), function (string $chip) use ($terms): bool {
            foreach ($terms as $term) {
                if (preg_match('/(?<![\p{L}\p{N}])' . preg_quote($term, '/') . '(?![\p{L}\p{N}])/u', $chip)) {
                    return false;
                }
            }
            return $chip !== '';
        });
        $block = $kept ? '[[next: ' . implode(' | ', $kept) . ']]' : '';

        return rtrim(substr($answer, 0, $m[0][1]) . $block . substr($answer, $m[0][1] + strlen($m[0][0])));
    }

    /**
     * The findings as one line each — for logs and tools/jonson/claims.php.
     *
     * @return string[]
     */
    public function problems(string $answer, string $context, array $employers, array $clients = []): array
    {
        return array_column($this->findings($answer, $context, $employers, $clients), 'problem');
    }

    /**
     * The answer without any sentence that names one of $names: the last resort when
     * a rewrite still gets it wrong. A sentence carrying a [[marker]] keeps it, so a
     * surface it introduced isn't lost with it.
     *
     * @param string[] $names
     */
    public function withoutSentences(string $answer, array $names): string
    {
        $paragraphs = preg_split('/(\n\s*\n)/u', $answer, -1, PREG_SPLIT_DELIM_CAPTURE);
        foreach ($paragraphs as $i => $paragraph) {
            if (str_starts_with(trim($paragraph), '[[')) {
                continue;
            }
            $sentences = preg_split('/(?<=[.!?])\s+(?=[A-Z"“‘(\[])/u', $paragraph);
            $kept = [];
            foreach ($sentences as $sentence) {
                $hit = false;
                foreach ($names as $name) {
                    if (str_contains($sentence, $name)) {
                        $hit = true;
                        break;
                    }
                }
                if (!$hit) {
                    $kept[] = $sentence;
                } elseif (preg_match_all('/\[\[[^\]]*\]\]/', $sentence, $m) && $kept) {
                    $kept[count($kept) - 1] .= implode('', $m[0]);
                }
            }
            $paragraphs[$i] = implode(' ', $kept);
        }

        return trim((string) preg_replace('/\n{3,}/', "\n\n", implode('', $paragraphs)));
    }

    /** The answer as it reads on screen: no markers, no links, no markdown. */
    private function plain(string $answer): string
    {
        $text = preg_replace('/\[\[[^\]]*\]\]/', '', $answer);
        $text = preg_replace('/\[([^\]]+)\]\([^)]*\)/', '$1', $text); // [label](url)
        $text = preg_replace('~https?://\S+~', '', $text);
        $text = str_replace(['**', '__', '`'], '', $text);

        return (string) $text;
    }

    /**
     * Names put forward as Jon's work that the context never mentions.
     *
     * @param string[] $clients
     * @return string[]
     */
    private function unknownClients(string $text, string $context, array $clients): array
    {
        $unknown = [];
        foreach ($this->claimedNames($text, $clients, $context) as $name) {
            if (!$this->isOneOf($name, $clients)) {
                $unknown[] = $name;
            }
        }

        return array_values(array_unique($unknown));
    }

    /**
     * Every name the answer offers as work: those after a WORKED phrase, and every
     * name in a list that holds a real client ("Lloyds, HSBC and Apple").
     *
     * @param string[] $clients
     * @return string[]
     */
    private function claimedNames(string $text, array $clients, string $context): array
    {
        $names = [];
        $list = $this->listPattern();
        if (preg_match_all('/\b(?i:' . self::WORKED . ')\s+(?:the\s+)?(' . $list . ')/u', $text, $m)) {
            foreach ($m[1] as $found) {
                array_push($names, ...$this->splitList($found));
            }
        }
        if (preg_match_all('/(?<![\w.])(' . $list . ')/u', $text, $m, PREG_OFFSET_CAPTURE)) {
            foreach ($m[1] as [$found, $offset]) {
                $members = $this->splitList($found);
                // "Yes, Vaiie…", "There's Lloyds…": a sentence's first word is capitalised
                // because it comes first, not because it's a name.
                $opens = $offset === 0 || preg_match('/[.!?:;—–\n]\s*["“‘(]?$/u', substr($text, 0, $offset));
                if ($opens && $members && $this->ordinaryWord($members[0], $context)) {
                    array_shift($members);
                }
                // A list says "and": "The MD, James Hirst, put it…" is one person, named twice.
                if (count($members) < 2 || !preg_match('/\band\b|&/u', $found)) {
                    continue;
                }
                foreach ($members as $member) {
                    if ($this->isOneOf($member, $clients)) {
                        array_push($names, ...$members);
                        break;
                    }
                }
            }
        }

        // Only names: a capital that isn't the narrator.
        return array_values(array_unique(array_filter($names, fn(string $n) =>
            preg_match('/^[A-Z0-9]/u', $n) && $this->keyWords($n)
            && !preg_match('/^I(?:[’\'](?:m|ve|d|ll))?$/u', $n))));
    }

    /**
     * A sentence-opening word that's ordinary prose, not a name: its lower-case form is
     * in the context ("yes", "there's", "event-wise"). A multi-word run loses just that
     * word: "There's Lloyds Bank International" is Lloyds.
     */
    private function ordinaryWord(string &$member, string $context): bool
    {
        $words = preg_split('/\s+/u', $member);
        $first = mb_strtolower($words[0]);
        $plain = $this->mentions($context, $first)
            || (str_ends_with($first, '-wise') && $this->mentions($context, substr($first, 0, -5)));
        if (!$plain) {
            return false;
        }
        if (count($words) > 1) {
            $member = implode(' ', array_slice($words, 1));
            return false;
        }

        return true;
    }

    /**
     * Names straight after an employment phrase that don't belong to a CV company.
     *
     * @param string[] $employers
     * @return string[]
     */
    private function notEmployers(string $text, array $employers): array
    {
        $wrong = [];
        if (!preg_match_all('/\b(?i:' . self::EMPLOYED . ')\s*(' . $this->listPattern() . ')/u', $text, $m)) {
            return [];
        }
        foreach ($m[1] as $found) {
            foreach ($this->splitList($found) as $one) {
                if (preg_match('/^[A-Z0-9]/u', $one) && $this->keyWords($one) && !$this->isOneOf($one, $employers)) {
                    $wrong[] = $one;
                }
            }
        }

        return array_values(array_unique($wrong));
    }

    /** A name, then more joined by commas / "and" / "&": "HSBC, Lloyds and Sure". */
    private function listPattern(): string
    {
        // A word may hold a dot ("Urban.co.uk") but not end on one: "Vaiie. Many" is two.
        $word = '[A-Z0-9](?:[\w&\'’-]|\.(?=\w))*';
        $name = "$word(?:[ \\t]+(?:(?:of|the|de|for)[ \\t]+)?$word)*";

        return "(?:both\\s+)?$name(?:\\s*(?:,|\\band\\b|&)\\s*(?:at\\s+|the\\s+)?$name)*";
    }

    /** @return string[] */
    private function splitList(string $found): array
    {
        $found = preg_replace('/^both\s+/iu', '', $found);
        $out = [];
        foreach (preg_split('/\s*(?:,|\band\b|&)\s*(?:at\s+|the\s+)?/u', $found) as $one) {
            $one = preg_replace('/[’\']s$/u', '', rtrim(trim($one), '.’\'-'));
            if ($one !== '') {
                $out[] = $one;
            }
        }

        return $out;
    }

    /** "HSBC" is "HSBC International"; "White Paper" is "The White Paper Conference Company". */
    private function isOneOf(string $name, array $companies): bool
    {
        $words = $this->keyWords($name);
        if (!$words) {
            return false; // "The" alone is nobody
        }
        foreach ($companies as $company) {
            $theirs = $this->keyWords($company);
            if (!array_diff($words, $theirs) || ($theirs && !array_diff($theirs, $words))) {
                return true;
            }
        }

        return false;
    }

    /** @return string[] */
    private function keyWords(string $name): array
    {
        $words = preg_split('/[^a-z0-9]+/', strtolower($name), -1, PREG_SPLIT_NO_EMPTY);

        return array_values(array_diff($words, [...self::JOINERS, ...self::GENERIC]));
    }

    /** Whole-word, case-sensitive: does the context use this word? */
    private function mentions(string $context, string $word): bool
    {
        $word = preg_replace('/[’\']s$/u', '', $word);
        if ($word === '') {
            return true;
        }

        return (bool) preg_match('/(?<![\w])' . preg_quote($word, '/') . '(?![\w])/u', $context);
    }
}
