columnSuffix: null
handle: auditStatus
instructions: null
name: Status
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Received
        -
          - value
          - received
        -
          - icon
          - ''
        -
          - color
          - '#96d35f'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'In review'
        -
          - value
          - in-review
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Failed
        -
          - value
          - failed
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Sent
        -
          - value
          - sent
        -
          - icon
          - ''
        -
          - color
          - '#96d35f'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Complete
        -
          - value
          - complete
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
