columnSuffix: null
handle: auditStatus
instructions: null
name: Status
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - submitted
        -
          - value
          - submitted
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - capturing
        -
          - value
          - capturing
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - ready
        -
          - value
          - ready
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - failed
        -
          - value
          - failed
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - approved
        -
          - value
          - approved
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - sent
        -
          - value
          - sent
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
