columnSuffix: null
handle: codeLanguage
instructions: null
name: Language
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Twig
        -
          - value
          - twig
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - SCSS
        -
          - value
          - scss
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - PHP
        -
          - value
          - php
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - JavaScript
        -
          - value
          - js
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - HTML
        -
          - value
          - html
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Shell
        -
          - value
          - shell
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
