columnSuffix: null
handle: ctaUrl
instructions: null
name: URL
searchable: false
settings:
  advancedFields:
    - target
  fullGraphqlData: false
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
            -
              - allowCustomSchemes
              - ''
      -
        - asset
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowedKinds
              - '*'
            -
              - showUnpermittedVolumes
              - ''
            -
              - showUnpermittedFiles
              - ''
  types:
    - url
    - email
    - tel
    - asset
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
