columnSuffix: null
handle: hasBreakout
instructions: null
name: 'Has breakout?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: 'Yes'
  showLabelsInCards: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
