columnSuffix: null
handle: hasLoopedAnimation
instructions: null
name: 'Loop Animation?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: 'Yes'
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
