columnSuffix: null
handle: isExcludedFromTools
instructions: null
name: 'Exclude from tools?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: 'Yes'
  showLabelsInCards: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
