columnSuffix: null
handle: jobPrompts
instructions: null
name: 'Job Prompts'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Prompt
            -
              - handle
              - prompt
            -
              - width
              - 100%
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - rowId
          - 5ef6f96e-515c-4a7a-970e-f15fd3d09895
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
