columnSuffix: null
handle: largeImage
instructions: null
name: 'Large Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: false
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:3e9036d0-de1a-4b49-a1fe-85cded2c7b73' # Local
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: thumbs
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:3e9036d0-de1a-4b49-a1fe-85cded2c7b73' # Local
  restrictedLocationSubpath: "{% set s = object.owner ?? object %}{% if (s.section.handle ?? '') == 'caseStudies' %}case-studies/{{ (s.clientSelector.one().title ?? s.slug)|kebab }}{% else %}{{ (s.section.handle ?? s.slug)|kebab }}{% endif %}"
  selectionLabel: null
  showSearchInput: false
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: thumbs
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
