columnSuffix: null
handle: partnershipPrompts
instructions: null
name: 'Partnership Prompts'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Prompt
            -
              - handle
              - prompt
            -
              - width
              - 100%
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - rowId
          - 0945aaf6-99aa-451c-a981-daad9bd4e755
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
