columnSuffix: null
handle: winWorkPrompts
instructions: null
name: 'Win Work Prompts'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Prompt
            -
              - handle
              - prompt
            -
              - width
              - 100%
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - rowId
          - 2b0d0b61-93d9-4e47-924f-a2b23559df74
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
