defaultPlacement: end
fieldLayouts:
  14b38266-0eeb-43d5-8702-093059b8b0d9:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-07-03T20:30:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 657a0e4b-fa82-45ac-8df0-f0a6be369c34
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6db484dd-d77b-4e34-8866-deff777181c7
        userCondition: null
    thumbFieldKey: null
handle: location
name: Location
siteSettings:
  6a0c33fd-98e1-48b8-a4d0-24e7132d1623: # Jon Leverrier
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 2
  uid: f4e88304-a447-46c8-9083-4ac20386664a
